version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: carangobom
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: postgres
      # You can use whatever password you like
      POSTGRES_PASSWORD: postgres
    ports:
      # <Port exposed> : < POSTGRES Port running inside container>
      - "5432:5432"
      # Where our data will be persisted
    volumes:
      - db-volume:/var/lib/postgresql/data
# Names our volume
volumes:
  db-volume:
