version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carangobom
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - '5432:5432'
    volumes:
    - db-volume:/var/lib/postgresql/data
volumes:
  db-volume: